/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.JsonParserTestSuite;
	import flexUnitTests.JsonParserTester;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var flexUnitTests_JsonParserTester_obj:flexUnitTests.JsonParserTester;
		
		private var flexUnitTests_JsonParserTestSuite_obj:flexUnitTests.JsonParserTestSuite;
	}
}